packages:
  - typescript

engineStrict: true
packageManagerStrict: true
saveExact: true
strictPeerDependencies: true
minimumReleaseAgeStrict: true
verifyDepsBeforeRun: error
storeDir: .cache/pnpm/store
enableGlobalVirtualStore: false
